name: ci-app

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run install
        run: make install
      - run: make npm run build
          needs: run install
      - run: make start
      - run: make test
      - run: make lint
